# -*- coding: utf-8 -*-
"""
/***************************************************************************
 APLS
                                 A QGIS plugin
 This plugin performs Average Path Length Similarity
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-06-11
        copyright            : (C) 2022 by Mohammed Nasser
        email                : momaabna2019@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load APLS class from file APLS.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .APLS import APLS
    return APLS(iface)
